/*************************************************************************
 * ALL ACTION TYPES
 *************************************************************************/
export enum actionTypes {

    //News
    GET_NEWS_FETCH_REQUEST = '@News/GET_NEWS_FETCH_REQUEST',
    GET_NEWS_FETCH_SUCCESS = '@News/GET_NEWS_FETCH_SUCCESS',
    GET_NEWS_FETCH_FAIL = '@News/GET_NEWS_FETCH_FAIL',

    GET_READ_ONE_NEWS_FETCH_REQUEST = '@News/GET_READ_ONE_NEWS_FETCH_REQUEST',
    GET_READ_ONE_NEWS_FETCH_SUCCESS = '@News/GET_READ_ONE_NEWS_FETCH_SUCCESS',
    GET_READ_ONE_NEWS_FETCH_FAIL = '@News/GET_READ_ONE_NEWS_FETCH_FAIL',

    POST_NEWS_FETCH_REQUEST = '@News/POST_NEWS_FETCH_REQUEST',
    POST_NEWS_FETCH_SUCCESS = '@News/POST_NEWS_FETCH_SUCCESS',
    POST_NEWS_FETCH_FAIL = '@News/POST_NEWS_FETCH_FAIL',

    DELETE_NEWS_FETCH_REQUEST = '@News/DELETE_NEWS_FETCH_REQUEST',
    DELETE_NEWS_FETCH_SUCCESS = '@News/DELETE_NEWS_FETCH_SUCCESS',
    DELETE_NEWS_FETCH_FAIL = '@News/DELETE_NEWS_FETCH_FAIL',

    UPDATE_NEWS_FETCH_REQUEST = '@News/UPDATE_NEWS_FETCH_REQUEST',
    UPDATE_NEWS_FETCH_SUCCESS = '@News/UPDATE_NEWS_FETCH_SUCCESS',
    UPDATE_NEWS_FETCH_FAIL = '@News/UPDATE_NEWS_FETCH_FAIL',

    CLEAR_NEWS_ERROR = '@News/CLEAR_NEWS_ERROR',


    //User
    USER_LOGIN_REQUEST = '@User/USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS = '@User/USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL = '@User/USER_LOGIN_FAIL',

    USER_INFO_FETCH_REQUEST = '@User/USER_INFO_FETCH_REQUEST',
    USER_INFO_FETCH_SUCCESS = '@User/USER_INFO_FETCH_SUCCESS',
    USER_INFO_FETCH_FAIL = '@User/USER_INFO_FETCH_FAIL',

    USER_LOGOUT = '@User/USER_LOGOUT',


    //Error Message
    SAVE_ERROR_MESSAGE = '@ErrorMessage/SAVE_ERROR_MESSAGE',
    CLEAR_ERROR_MESSAGE = '@ErrorMessage/CLEAR_ERROR_MESSAGE',
}
